%%
function verbose(info, param, problem, iter)

if param.verbose == 1
    T = param.T;
    N = param.N;
    
    stats = info(iter);
    
    cost = stats.cost;
    var = stats.variance;
    con = stats.consensus;
    err = stats.error;
    distVa = stats.distVa;
    grnorm = stats.gradnorm;
    stopCond = stats.stopCond;
    name = problem.name;
    mode = param.mode;
    
    msg = sprintf([
        ' %s \n', ...
        ' *****************************************\n\n', ...
        ' Noise: \t \t %s\n', ...
        ' max. Iterations: \t %i\n', ...
        ' Iterations: \t \t %i\n', ...
        ' Number of Particles: \t %i\n', ...
        ' Variance: \t \t %.2e\n', ...
        ' Consensus: \t \t %.2e\n', ...
        ' Change in Va: \t \t %.2e\n', ...
        ' Gradient norm: \t %.2e\n', ...
        ' Cost: \t \t \t %.2e\n', ...
        ' Error: \t \t %.2e\n', ...
        ' Stopping Condition: \t %s\n'], ...
        name, mode, T, iter, N, var, con, distVa, grnorm, cost, err, stopCond);
    
    reverseStr = repmat(sprintf('\b'), 1, length(msg));
    
    fprintf([reverseStr msg]);

end

end